# Install dependencies.
install:
  - sh <(curl -q https://platform.activestate.com/dl/cli/install.sh) --activate-default KadaliKiranKumar/Python-3.8.2-Linux-CentOS-Windows

before_script:
  - state pull
# Run linting and tests.
script:
  - state run lints
  - state run tests

# Turn email notifications off.
notifications:
  email: false