# Install dependencies.
install:
  - sh <(curl -q https://platform.activestate.com/dl/cli/install.sh) -n

before_script:
  - state pull
# Run linting and tests.
script:
  - state run lints
  - state run tests

# Turn email notifications off.
notifications:
  email: false